# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c210f85fabbf2a112d0a98c83d4ee44cbe82b431d412996c948f590aca078d06ef07da380401d9fde989752325c1e753423b37cca737aaf34c7e726f63d44403

test:
  secret_key_base: ca52fdb7bc1e34511ae82b76b8ebae84406e1ee08b7758016c2fa59b683c33d6a84ec469ac221f14e840856671e7949554c9415283b0146a61003622d9850d35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
